pipeline {
    agent any

    environment {
        GIT_URL = 'https://github.com/whvt/py_course'
        GIT_CREDENTIALS = 'GITHUB_CREDENTIALS'
        DOCKER_IMAGE = 'HW30'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'feature/homework31', credentialsId: "$GIT_CREDENTIALS", url: "$GIT_URL"
            }
        }

        stage('Build & Test') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
                sh 'docker run --rm $DOCKER_IMAGE pytest -v --alluredir=reports'
            }
        }

        stage('Generate Allure Report') {
            steps {
                sh 'allure generate reports -o reports_html'
            }
        }

        stage('Publish Report') {
            steps {
                allure([
                    results: [[path: 'reports_html']]
                ])
            }
        }
    }
}
